#!/usr/bin/python
import os
import sys
import argparse
from subprocess import call


parser = argparse.ArgumentParser()

parser.add_argument("-m", "--make", action="store_true", help="Make clean and make before loading.")
args = parser.parse_args()

if args.make:
	os.system("make clean")
	os.system("make")


os.system("propeller-elf-size main.elf")
sys.exit(os.system("propeller-load -r -q -t115200 main.elf"))

