all:
	$(MAKE) -C cog
	$(MAKE) -C cmm
	$(MAKE) -C lmm
	$(MAKE) -C xmm
	$(MAKE) -C xmmc

clean:
	$(MAKE) -C cog clean
	$(MAKE) -C cmm clean
	$(MAKE) -C lmm clean
	$(MAKE) -C xmm clean
	$(MAKE) -C xmmc clean
