set(SIMPLE_OBJECTS
        ../VGA.spin
        ../abvolts.c
        ../abvoltsDA.c
        ../abvoltsF.c
        ../adcACpropab.c
        ../adcACpropab.cogc
        ../adcDCVpropab.c
        ../adcDCpropab.c
        ../addfiledriver.c
        ../cogend.c
        ../cognum.c
        ../cogrun.c
        ../colorpal.c
        ../compass3d.c
        ../count.c
        ../daCalibrate.c
        ../daVolts.c
        ../dac.c
        ../dacctr.c
        ../doscanf.c
        ../dosprint.c
        ../dosput.c
        ../dprint.c
        ../dprinti.c
        ../dscan.c
        ../dscani.c
        ../eeprom_getByte.c
        ../eeprom_getFloat.c
        ../eeprom_getInt.c
        ../eeprom_getStr.c
        ../eeprom_init.c
        ../eeprom_putByte.c
        ../eeprom_putFloat.c
        ../eeprom_putInt.c
        ../eeprom_putStr.c
        ../endianSwap.c
        ../fdserial.c
        ../fdserial_utils.c
        ../floatToString.c
        ../freqout.c
        ../gRangec.c
        ../getBin.c
        ../getChar.c
        ../getDec.c
        ../getDirection.c
        ../getDirections.c
        ../getFloat.c
        ../getHex.c
        ../getMode.c
        ../getOutput.c
        ../getOutputs.c
        ../getScale.c
        ../getState.c
        ../getStates.c
        ../getStr.c
        ../gets.c
        ../getxyz10.c
        ../getxyz8.c
        ../high.c
        ../i2c_busy.c
        ../i2c_in.c
        ../i2c_init.c
        ../i2c_out.c
        ../init.c
        ../input.c
        ../intprint.c
        ../itoa.c
        ../low.c
        ../mark.c
        ../mma7455.c
        ../mstimer.c
        ../mx2125.c
        ../mx2125_accel.c
        ../mx2125_rotate.c
        ../mx2125_tilt.c
        ../pause.c
        ../pause_us.c
        ../ping.c
        ../print.c
        ../printNumber.c
        ../printi.c
        ../pst.spin
        ../pulseIn.c
        ../pulseOut.c
        ../putBin.c
        ../putBinDigits.c
        ../putChar.c
        ../putDec.c
        ../putDecDigits.c
        ../putFloat.c
        ../putFloatPrecision.c
        ../putHex.c
        ../putHexDigits.c
        ../putLine.c
        ../putStr.c
        ../putStrDigits.c
        ../putln.c
        ../pwm.c
        ../rcTime.c
        ../readByte.c
        ../reverse.c
        ../rfidser.c
        ../safe_gets.c
        ../scan.c
        ../scanf_getf.c
        ../scanf_getl.c
        ../sddriverconfig.c
        ../serial_close.c
        ../serial_open.c
        ../serial_rxtx.c
        ../servo.c
        ../servoAux.c
        ../servodiffdrive.c
        ../setDacBits.c
        ../setDirection.c
        ../setDirections.c
        ../setIoDt.c
        ../setMode.c
        ../setOffset.c
        ../setOutput.c
        ../setOutputs.c
        ../setPauseDt.c
        ../setStates.c
        ../setTimeout.c
        ../shiftIn.c
        ../shiftOut.c
        ../simplei2c.c
        ../simpleterm.c
        ../simpleterm_close.c
        ../sirc.c
        ../soundimpact.c
        ../sprint.c
        ../sprinti.c
        ../squareWave.c
        ../sscan.c
        ../stringToFloat.c
        ../timeTicks.c
        ../timeout.c
        ../toggle.c
        ../vgatext.c
        ../wait.c
        ../wavplayer.c
        ../writeBin.c
        ../writeBinDigits.c
        ../writeByte.c
        ../writeChar.c
        ../writeDec.c
        ../writeDecDigits.c
        ../writeFloat.c
        ../writeFloatPrecision.c
        ../writeHex.c
        ../writeHexDigits.c
        ../writeLine.c
        ../writeStr.c
        ../writeStrDigits.c)