set(SIMPLE_OBJECTS
        ../abvolts
        ../abvoltsDA
        ../abvoltsF
        ../adcACpropab
        ../adcDCVpropab
        ../adcDCpropab
        ../addfiledriver
        ../cogend
        ../cognum
        ../cogrun
        ../colorpal
        ../compass3d
        ../count
        ../daCalibrate
        ../daVolts
        ../dac
        ../dacctr
        ../doscanf
        ../dosprint
        ../dosput
        ../dprint
        ../dprinti
        ../dscan
        ../dscani
        ../eeprom_getByte
        ../eeprom_getFloat
        ../eeprom_getInt
        ../eeprom_getStr
        ../eeprom_init
        ../eeprom_putByte
        ../eeprom_putFloat
        ../eeprom_putInt
        ../eeprom_putStr
        ../endianSwap
        ../fdserial
        ../fdserial_utils
        ../floatToString
        ../freqout
        ../gRangec
        ../getBin
        ../getChar
        ../getDec
        ../getDirection
        ../getDirections
        ../getFloat
        ../getHex
        ../getMode
        ../getOutput
        ../getOutputs
        ../getScale
        ../getState
        ../getStates
        ../getStr
        ../gets
        ../getxyz10
        ../getxyz8
        ../high
        ../i2c_busy
        ../i2c_in
        ../i2c_init
        ../i2c_out
        ../init
        ../input
        ../intprint
        ../itoa
        ../low
        ../mark
        ../mma7455
        ../mstimer
        ../mx2125
        ../mx2125_accel
        ../mx2125_rotate
        ../mx2125_tilt
        ../pause
        ../pause_us
        ../ping
        ../print
        ../printNumber
        ../printi
        ../pulseIn
        ../pulseOut
        ../putBin
        ../putBinDigits
        ../putChar
        ../putDec
        ../putDecDigits
        ../putFloat
        ../putFloatPrecision
        ../putHex
        ../putHexDigits
        ../putLine
        ../putStr
        ../putStrDigits
        ../putln
        ../pwm
        ../rcTime
        ../readByte
        ../reverse
        ../rfidser
        ../safe_gets
        ../scan
        ../scanf_getf
        ../scanf_getl
        ../sddriverconfig
        ../serial_close
        ../serial_open
        ../serial_rxtx
        ../servo
        ../servoAux
        ../servodiffdrive
        ../setDacBits
        ../setDirection
        ../setDirections
        ../setIoDt
        ../setMode
        ../setOffset
        ../setOutput
        ../setOutputs
        ../setPauseDt
        ../setStates
        ../setTimeout
        ../shiftIn
        ../shiftOut
        ../simplei2c
        ../simpleterm
        ../simpleterm_close
        ../sirc
        ../soundimpact
        ../sprint
        ../sprinti
        ../squareWave
        ../sscan
        ../stringToFloat
        ../timeTicks
        ../timeout
        ../toggle
        ../vgatext
        ../wait
        ../wavplayer
        ../writeBin
        ../writeBinDigits
        ../writeByte
        ../writeChar
        ../writeDec
        ../writeDecDigits
        ../writeFloat
        ../writeFloatPrecision
        ../writeHex
        ../writeHexDigits
        ../writeLine
        ../writeStr
        ../writeStrDigits)