all:
	$(MAKE) -C cog
	$(MAKE) -C cmm
	$(MAKE) -C lmm
	$(MAKE) -C xmmc
	$(MAKE) -C xmm-single
	$(MAKE) -C xmm-split

clean:
	$(MAKE) -C cog clean
	$(MAKE) -C cmm clean
	$(MAKE) -C lmm clean
	$(MAKE) -C xmmc clean
	$(MAKE) -C xmm-single clean
	$(MAKE) -C xmm-split clean
