set(CMAKE_ECOGCXX_COMPILER "/opt/parallax/bin/propeller-elf-gcc")
set(CMAKE_ECOGCXX_COMPILER_ARG1 "")
set(CMAKE_ECOGCXX_COMPILER_ID "")
set(CMAKE_ECOGCXX_COMPILER_VERSION "")
set(CMAKE_ECOGCXX_PLATFORM_ID "")
set(CMAKE_ECOGCXX_SIMULATE_ID "")
set(CMAKE_ECOGCXX_SIMULATE_VERSION "")

set(CMAKE_AR "")
set(CMAKE_RANLIB "/opt/parallax/bin/propeller-elf-ranlib")
set(CMAKE_LINKER "")
set(CMAKE_COMPILER_IS_GNUCC )
set(CMAKE_ECOGCXX_COMPILER_LOADED 1)
set(CMAKE_ECOGCXX_COMPILER_WORKS )
set(CMAKE_ECOGCXX_ABI_COMPILED )
set(CMAKE_COMPILER_IS_MINGW )
set(CMAKE_COMPILER_IS_CYGWIN )

set(CMAKE_ECOGCXX_COMPILER_ENV_VAR "CXX")

set(CMAKE_ECOGCXX_COMPILER_ID_RUN 1)
set(CMAKE_ECOGCXX_IGNORE_EXTENSIONS inl;h;hpp;HPP;H;o;O;obj;OBJ;def;DEF;rc;RC)
set(CMAKE_ECOGCXX_SOURCE_FILE_EXTENSIONS ecogC;ecogM;ecogc++;ecogcpp;ecogcxx;ecogm;ecogmm;ecogCPP)
set(CMAKE_ECOGCXX_LINKER_PREFERENCE 70)

set(LINKER_LANGUAGE C)
# Save compiler ABI information.
set(CMAKE_ECOGCXX_SIZEOF_DATA_PTR "")
set(CMAKE_ECOGCXX_COMPILER_ABI "")
set(CMAKE_ECOGCXX_LIBRARY_ARCHITECTURE "")

if(CMAKE_ECOGCXX_SIZEOF_DATA_PTR)
  set(CMAKE_SIZEOF_VOID_P "${CMAKE_CXX_SIZEOF_DATA_PTR}")
endif()

if(CMAKE_ECOGCXX_COMPILER_ABI)
  set(CMAKE_INTERNAL_PLATFORM_ABI "${CMAKE_CXX_COMPILER_ABI}")
endif()

if(CMAKE_ECOGCXX_LIBRARY_ARCHITECTURE)
  set(CMAKE_LIBRARY_ARCHITECTURE "")
endif()




set(CMAKE_ECOGCXX_IMPLICIT_LINK_LIBRARIES "")
set(CMAKE_ECOGCXX_IMPLICIT_LINK_DIRECTORIES "")
set(CMAKE_ECOGCXX_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES "")



