set(CMAKE_COGCXX_COMPILER "/opt/parallax/bin/propeller-elf-gcc")
set(CMAKE_COGCXX_COMPILER_ARG1 "")
set(CMAKE_COGCXX_COMPILER_ID "")
set(CMAKE_COGCXX_COMPILER_VERSION "")
set(CMAKE_COGCXX_PLATFORM_ID "")
set(CMAKE_COGCXX_SIMULATE_ID "")
set(CMAKE_COGCXX_SIMULATE_VERSION "")

set(CMAKE_AR "")
set(CMAKE_RANLIB "/opt/parallax/bin/propeller-elf-ranlib")
set(CMAKE_LINKER "")
set(CMAKE_COMPILER_IS_GNUCC )
set(CMAKE_COGCXX_COMPILER_LOADED 1)
set(CMAKE_COGCXX_COMPILER_WORKS )
set(CMAKE_COGCXX_ABI_COMPILED )
set(CMAKE_COMPILER_IS_MINGW )
set(CMAKE_COMPILER_IS_CYGWIN )

set(CMAKE_COGCXX_COMPILER_ENV_VAR "CXX")

set(CMAKE_COGCXX_COMPILER_ID_RUN 1)
set(CMAKE_COGCXX_IGNORE_EXTENSIONS inl;h;hpp;HPP;H;o;O;obj;OBJ;def;DEF;rc;RC)
set(CMAKE_COGCXX_SOURCE_FILE_EXTENSIONS cogC;cogM;cogc++;cogcpp;cogcxx;cogm;cogmm;cogCPP)
set(CMAKE_COGCXX_LINKER_PREFERENCE 70)

set(LINKER_LANGUAGE C)
# Save compiler ABI information.
set(CMAKE_COGCXX_SIZEOF_DATA_PTR "")
set(CMAKE_COGCXX_COMPILER_ABI "")
set(CMAKE_COGCXX_LIBRARY_ARCHITECTURE "")

if(CMAKE_COGCXX_SIZEOF_DATA_PTR)
  set(CMAKE_SIZEOF_VOID_P "${CMAKE_CXX_SIZEOF_DATA_PTR}")
endif()

if(CMAKE_COGCXX_COMPILER_ABI)
  set(CMAKE_INTERNAL_PLATFORM_ABI "${CMAKE_CXX_COMPILER_ABI}")
endif()

if(CMAKE_COGCXX_LIBRARY_ARCHITECTURE)
  set(CMAKE_LIBRARY_ARCHITECTURE "")
endif()




set(CMAKE_COGCXX_IMPLICIT_LINK_LIBRARIES "")
set(CMAKE_COGCXX_IMPLICIT_LINK_DIRECTORIES "")
set(CMAKE_COGCXX_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES "")



