set(CMAKE_ECOGC_COMPILER "/opt/parallax/bin/propeller-elf-gcc")
set(CMAKE_ECOGC_COMPILER_ARG1 "")
set(CMAKE_ECOGC_COMPILER_ID "")
set(CMAKE_ECOGC_COMPILER_VERSION "")
set(CMAKE_ECOGC_PLATFORM_ID "")
set(CMAKE_ECOGC_SIMULATE_ID "")
set(CMAKE_ECOGC_SIMULATE_VERSION "")

set(CMAKE_AR "")
set(CMAKE_RANLIB "/opt/parallax/bin/propeller-elf-ranlib")
set(CMAKE_LINKER "")
set(CMAKE_COMPILER_IS_GNUCC )
set(CMAKE_ECOGC_COMPILER_LOADED 1)
set(CMAKE_ECOGC_COMPILER_WORKS )
set(CMAKE_ECOGC_ABI_COMPILED )
set(CMAKE_COMPILER_IS_MINGW )
set(CMAKE_COMPILER_IS_CYGWIN )

set(CMAKE_ECOGC_COMPILER_ENV_VAR "CC")

set(CMAKE_ECOGC_COMPILER_ID_RUN 1)
set(CMAKE_ECOGC_SOURCE_FILE_EXTENSIONS ecogc)
set(CMAKE_ECOGC_IGNORE_EXTENSIONS h;H;o;O;obj;OBJ;def;DEF;rc;RC)
set(CMAKE_ECOGC_LINKER_PREFERENCE 50)

# Save compiler ABI information.
set(CMAKE_ECOGC_SIZEOF_DATA_PTR "")
set(CMAKE_ECOGC_COMPILER_ABI "")
set(CMAKE_ECOGC_LIBRARY_ARCHITECTURE "")

if(CMAKE_ECOGC_SIZEOF_DATA_PTR)
  set(CMAKE_SIZEOF_VOID_P "${CMAKE_C_SIZEOF_DATA_PTR}")
endif()

if(CMAKE_ECOGC_COMPILER_ABI)
  set(CMAKE_INTERNAL_PLATFORM_ABI "${CMAKE_C_COMPILER_ABI}")
endif()

if(CMAKE_ECOGC_LIBRARY_ARCHITECTURE)
  set(CMAKE_LIBRARY_ARCHITECTURE "")
endif()




set(CMAKE_ECOGC_IMPLICIT_LINK_LIBRARIES "")
set(CMAKE_ECOGC_IMPLICIT_LINK_DIRECTORIES "")
set(CMAKE_ECOGC_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES "")



