set(CMAKE_COGC_COMPILER "/opt/parallax/bin/propeller-elf-gcc")
set(CMAKE_COGC_COMPILER_ARG1 "")
set(CMAKE_COGC_COMPILER_ID "")
set(CMAKE_COGC_COMPILER_VERSION "")
set(CMAKE_COGC_PLATFORM_ID "")
set(CMAKE_COGC_SIMULATE_ID "")
set(CMAKE_COGC_SIMULATE_VERSION "")

set(CMAKE_AR "")
set(CMAKE_RANLIB "/opt/parallax/bin/propeller-elf-ranlib")
set(CMAKE_LINKER "")
set(CMAKE_COMPILER_IS_GNUCC )
set(CMAKE_COGC_COMPILER_LOADED 1)
set(CMAKE_COGC_COMPILER_WORKS )
set(CMAKE_COGC_ABI_COMPILED )
set(CMAKE_COMPILER_IS_MINGW )
set(CMAKE_COMPILER_IS_CYGWIN )

set(CMAKE_COGC_COMPILER_ENV_VAR "CC")

set(CMAKE_COGC_COMPILER_ID_RUN 1)
set(CMAKE_COGC_SOURCE_FILE_EXTENSIONS cogc)
set(CMAKE_COGC_IGNORE_EXTENSIONS h;H;o;O;obj;OBJ;def;DEF;rc;RC)
set(CMAKE_COGC_LINKER_PREFERENCE 50)

# Save compiler ABI information.
set(CMAKE_COGC_SIZEOF_DATA_PTR "")
set(CMAKE_COGC_COMPILER_ABI "")
set(CMAKE_COGC_LIBRARY_ARCHITECTURE "")

if(CMAKE_COGC_SIZEOF_DATA_PTR)
  set(CMAKE_SIZEOF_VOID_P "${CMAKE_C_SIZEOF_DATA_PTR}")
endif()

if(CMAKE_COGC_COMPILER_ABI)
  set(CMAKE_INTERNAL_PLATFORM_ABI "${CMAKE_C_COMPILER_ABI}")
endif()

if(CMAKE_COGC_LIBRARY_ARCHITECTURE)
  set(CMAKE_LIBRARY_ARCHITECTURE "")
endif()




set(CMAKE_COGC_IMPLICIT_LINK_LIBRARIES "")
set(CMAKE_COGC_IMPLICIT_LINK_DIRECTORIES "")
set(CMAKE_COGC_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES "")



