install(DIRECTORY .
	DESTINATION PropWare
	PATTERN *.py PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ
	PATTERN CMakeFiles EXCLUDE
	PATTERN _CPack_Packages EXCLUDE
	PATTERN util/__pycache__
	PATTERN .idea EXCLUDE
	PATTERN .settings EXCLUDE
	PATTERN .git EXCLUDE
	PATTERN .gitignore EXCLUDE
	PATTERN .gitattributes EXCLUDE
	PATTERN docs/docbook EXCLUDE
	PATTERN docs/html EXCLUDE
	PATTERN docs/latex EXCLUDE
	PATTERN docs/man EXCLUDE
	PATTERN .external_downloads EXCLUDE
	PATTERN cmake_install.cmake EXCLUDE
	PATTERN Makefile EXCLUDE
	PATTERN *.zip EXCLUDE
	PATTERN *.i EXCLUDE
	PATTERN *.ii EXCLUDE
	REGEX bin/.*\\.s EXCLUDE
	PATTERN *.pyc EXCLUDE)

