# #########################################################
# this makefile allows building and cleaning the toggle demo
#
# Copyright (c) 2011 Steve Denson
# MIT Licensed
# #########################################################

CFLAGS = -Os

#
# objects for this program
#

PRJ = SPI_Demo

NAME = $(PRJ)
OBJS = $(PRJ).o spi.o spi_as.o
BOARD = QUICKSTART
MODEL = lmm

all: $(NAME).elf

include /mnt/win-7/Users/Public/Kits/Embedded/Parallax/Library/common.mk
