all:
	$(MAKE) -C HD44780/Debug -f ../Makefile
	$(MAKE) -C L3G/Debug -f ../Makefile
	$(MAKE) -C MAX6675/Debug -f ../Makefile
	$(MAKE) -C MCP300x/Debug -f ../Makefile
	$(MAKE) -C SD/Debug -f ../Makefile
	$(MAKE) -C SPI/Debug -f ../Makefile
	
clean:
	$(MAKE) -C HD44780/Debug -f ../Makefile clean
	$(MAKE) -C L3G/Debug -f ../Makefile clean
	$(MAKE) -C MAX6675/Debug -f ../Makefile clean
	$(MAKE) -C MCP300x/Debug -f ../Makefile clean
	$(MAKE) -C SD/Debug -f ../Makefile clean
	$(MAKE) -C SPI/Debug -f ../Makefile clean