CFLAGS = -Os

PRJ = SD_Demo

NAME = $(PRJ)
OBJS = $(PRJ).o sd.o spi.o spi_as.o
BOARD = QUICKSTART
MODEL = lmm

all: $(NAME).elf

include /mnt/win-7/Users/Public/Kits/Embedded/Parallax/Library/common.mk
